import { fileURLToPath } from "node:url";
import {
  and,
  asc,
  count,
  desc,
  eq,
  exists,
  ilike,
  inArray,
  ne,
  notExists,
  notInArray,
  or,
  sql,
  type SQL,
} from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
import pg from "pg";
import {
  ALL_TOPIC_IDS,
  type LanguageId,
  type RoundKind,
  type RoundVote,
  type TopicId,
} from "@guessly/protocol";
import {
  answerKey,
  type BankedRound,
  type BankedRoundRecord,
  type BankedRoundText,
  type NewBankedRound,
  type RoundOrder,
  type RoundRepository,
  type RoundVoteTally,
  type TopicStock,
} from "./repository.js";
import { rounds, roundTexts, roundVotes } from "./schema.js";

/**
 * The bank on Postgres, through Drizzle. Right for what the bank actually is:
 * one database written by the fill tool and read by the game server — two
 * processes sharing a server built for exactly that.
 *
 * The schema lives in `schema.ts` and the SQL that builds it in `drizzle/`,
 * generated by `drizzle-kit generate` from the same file the queries import —
 * so the tables the migrations make are the tables the queries mean, by
 * construction. `init()` applies whatever is pending, which keeps the old
 * contract: everything after it may assume the schema is there.
 *
 * The same queries serve two databases: the real one over `pg`, and — for the
 * tests — PGlite, which is Postgres itself compiled to WASM, not an imitation
 * of it. See `memory.ts`. This type is the seam between them: everything both
 * drivers can do, and everything the repository needs.
 */
export type BankDatabase = PgDatabase<PgQueryResultHKT, Record<string, never>>;

/** Where `drizzle-kit generate` writes: one level up from src/ and dist/ alike. */
export const migrationsFolder = fileURLToPath(new URL("../drizzle", import.meta.url));

interface RoundRow {
  id: number;
  topic: string;
  kind: string;
  subject: string;
  imageFile: string | null;
  sourceUrl: string | null;
  snippet: string | null;
  snippetLanguage: string | null;
}

const toBankedRound = (row: RoundRow, texts: BankedRound["texts"]): BankedRound => ({
  id: row.id,
  topic: row.topic as TopicId,
  kind: row.kind as RoundKind,
  subject: row.subject,
  imageFile: row.imageFile,
  sourceUrl: row.sourceUrl,
  snippet: row.snippet,
  snippetLanguage: row.snippetLanguage,
  texts,
});

const NO_VOTES: RoundVoteTally = { up: 0, down: 0 };

const toRecord = (
  row: RoundRow & { createdAt: number; timesServed: number; lastServedAt: number | null },
  texts: BankedRound["texts"],
  votes: RoundVoteTally,
): BankedRoundRecord => ({
  ...toBankedRound(row, texts),
  createdAt: row.createdAt,
  timesServed: row.timesServed,
  lastServedAt: row.lastServedAt,
  votes,
});

/** The whole `rounds` row, for the reads that want the ledger too. */
const recordColumns = {
  id: rounds.id,
  topic: rounds.topic,
  kind: rounds.kind,
  subject: rounds.subject,
  imageFile: rounds.imageFile,
  sourceUrl: rounds.sourceUrl,
  snippet: rounds.snippet,
  snippetLanguage: rounds.snippetLanguage,
  createdAt: rounds.createdAt,
  timesServed: rounds.timesServed,
  lastServedAt: rounds.lastServedAt,
};

/**
 * A search term as a LIKE pattern that matches it literally: the three
 * characters LIKE reads as syntax are escaped with Postgres's default escape,
 * so "100%" finds "100%" rather than everything starting with 100.
 */
const containing = (term: string): string =>
  `%${term.replace(/[\\%_]/g, (character) => `\\${character}`)}%`;

/**
 * How many thumbs of one kind a round has, as something the list can sort
 * by. A correlated count rather than a join onto a grouped tally, so the
 * plain order — newest, which never asks — pays nothing for the votes
 * existing, and a ranked page is one probe of `round_votes_round` per
 * candidate row: milliseconds for a bank of thousands.
 */
const thumbs = (vote: RoundVote): SQL<number> =>
  sql<number>`(SELECT count(*) FROM ${roundVotes} WHERE ${roundVotes.roundId} = ${rounds.id} AND ${roundVotes.vote} = ${vote})`;

/**
 * The list's ORDER BY. A ranking by one thumb is broken by the other and
 * then by newest: two rounds liked four times are told apart by which was
 * disliked less, and two nobody has judged read as the plain list does.
 */
const ordering = (order: RoundOrder): SQL[] => {
  switch (order) {
    case "newest":
      return [desc(rounds.id)];
    case "liked":
      return [desc(thumbs("up")), asc(thumbs("down")), desc(rounds.id)];
    case "disliked":
      return [desc(thumbs("down")), asc(thumbs("up")), desc(rounds.id)];
  }
};

const toTextRow = (roundId: number, language: LanguageId, text: BankedRoundText) => ({
  roundId,
  language,
  question: text.question,
  answer: text.answer,
  answerKey: answerKey(text.answer),
  aliases: text.aliases,
});

/**
 * The repository's queries, against whichever Postgres the caller opened.
 * `open` insists init() ran first; `end` is the driver's own goodbye.
 */
export function createDrizzleRoundRepository(options: {
  connect: () => Promise<BankDatabase>;
  end: () => Promise<void>;
}): RoundRepository {
  let db: BankDatabase | null = null;

  /** Init is the only place `db` is assigned; everything else may insist on it. */
  const open = (): BankDatabase => {
    if (db === null) throw new Error("round repository used before init()");
    return db;
  };

  /**
   * Every language each of these rounds was written in, gathered back into
   * one object per round. One query however many rounds, so a page of the
   * list costs two round trips rather than one per row. Takes the database
   * rather than opening it, so a transaction can read through itself.
   */
  const textsForAll = async (
    db: BankDatabase,
    roundIds: readonly number[],
  ): Promise<Map<number, BankedRound["texts"]>> => {
    const texts = new Map<number, BankedRound["texts"]>();
    if (roundIds.length === 0) return texts;

    const rows = await db
      .select({
        roundId: roundTexts.roundId,
        language: roundTexts.language,
        question: roundTexts.question,
        answer: roundTexts.answer,
        aliases: roundTexts.aliases,
      })
      .from(roundTexts)
      .where(inArray(roundTexts.roundId, [...roundIds]))
      .orderBy(asc(roundTexts.roundId), asc(roundTexts.language));

    for (const row of rows) {
      const own = texts.get(row.roundId) ?? {};
      own[row.language as LanguageId] = {
        question: row.question,
        answer: row.answer,
        aliases: row.aliases,
      };
      texts.set(row.roundId, own);
    }
    return texts;
  };

  /** Every language one round was written in, gathered back into one object. */
  const textsFor = async (roundId: number, db: BankDatabase = open()): Promise<BankedRound["texts"]> =>
    (await textsForAll(db, [roundId])).get(roundId) ?? {};

  /**
   * How each of these rounds has been received, counted in the database and
   * gathered per round — the same one-query-per-page shape as `textsForAll`,
   * and for the same reason. A round nobody has voted on is simply absent
   * from the map; the caller reads that as zero and zero.
   */
  const votesForAll = async (
    db: BankDatabase,
    roundIds: readonly number[],
  ): Promise<Map<number, RoundVoteTally>> => {
    const tallies = new Map<number, RoundVoteTally>();
    if (roundIds.length === 0) return tallies;

    const rows = await db
      .select({ roundId: roundVotes.roundId, vote: roundVotes.vote, n: count() })
      .from(roundVotes)
      .where(inArray(roundVotes.roundId, [...roundIds]))
      .groupBy(roundVotes.roundId, roundVotes.vote);

    for (const row of rows) {
      const own = tallies.get(row.roundId) ?? { ...NO_VOTES };
      if (row.vote === "up") own.up = row.n;
      else if (row.vote === "down") own.down = row.n;
      tallies.set(row.roundId, own);
    }
    return tallies;
  };

  /**
   * These rounds with their ledgers, every language and their votes, newest
   * first, through whichever database. Only the ones that exist: an id
   * nobody holds is simply not in the answer.
   */
  const recordsFor = async (db: BankDatabase, ids: readonly number[]): Promise<BankedRoundRecord[]> => {
    if (ids.length === 0) return [];
    const rows = await db
      .select(recordColumns)
      .from(rounds)
      .where(inArray(rounds.id, [...ids]))
      .orderBy(desc(rounds.id));
    const found = rows.map((row) => row.id);
    const [texts, votes] = await Promise.all([textsForAll(db, found), votesForAll(db, found)]);
    return rows.map((row) => toRecord(row, texts.get(row.id) ?? {}, votes.get(row.id) ?? NO_VOTES));
  };

  /** One round with its ledger and every language, through whichever database. */
  const recordFor = async (db: BankDatabase, id: number): Promise<BankedRoundRecord | null> =>
    (await recordsFor(db, [id]))[0] ?? null;

  /**
   * Does the topic already answer to this word in this language, on a round
   * other than `except`? The one rule both `insert` and `update` enforce,
   * written once so they cannot drift.
   */
  const clashFor = async (
    db: BankDatabase,
    topic: string,
    language: string,
    answer: string,
    except: number | null,
  ): Promise<{ id: number; answer: string } | null> => {
    const [clash] = await db
      .select({ id: roundTexts.roundId, answer: roundTexts.answer })
      .from(roundTexts)
      .innerJoin(rounds, eq(rounds.id, roundTexts.roundId))
      .where(
        and(
          eq(rounds.topic, topic),
          eq(roundTexts.language, language),
          eq(roundTexts.answerKey, answerKey(answer)),
          ...(except === null ? [] : [ne(roundTexts.roundId, except)]),
        ),
      )
      .limit(1);
    return clash ?? null;
  };

  /**
   * What `delete` and `deleteMany` both are: read what is about to go, then
   * remove it, in one transaction so the record handed back is the record
   * that went. The texts go with the rounds — the foreign key cascades.
   */
  const deleteMany = async (ids: readonly number[]): Promise<BankedRoundRecord[]> => {
    if (ids.length === 0) return [];
    return await open().transaction(async (tx) => {
      const records = await recordsFor(tx, ids);
      if (records.length === 0) return records;
      await tx.delete(rounds).where(
        inArray(
          rounds.id,
          records.map((record) => record.id),
        ),
      );
      return records;
    });
  };

  return {
    async init() {
      db = await options.connect();
    },

    async insert(round: NewBankedRound, now: number, served: boolean) {
      const languages = Object.keys(round.texts) as LanguageId[];
      if (languages.length === 0) return false;

      // Checked, then written, under a transaction-scoped advisory lock on
      // the topic: the fill tool and the game server are separate processes
      // on one database, and the lock is what keeps a check and its insert
      // from interleaving with another writer's — the same promise BEGIN
      // IMMEDIATE used to make, scoped to the one topic being written. The
      // check is a check rather than a unique index because the answer being
      // looked for lives one table away from the topic that scopes it.
      return await open().transaction(async (tx) => {
        await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${round.topic}))`);

        for (const language of languages) {
          const text = round.texts[language];
          if (text === undefined) continue;
          if ((await clashFor(tx, round.topic, language, text.answer, null)) !== null) return false;
        }

        const [inserted] = await tx
          .insert(rounds)
          .values({
            topic: round.topic,
            kind: round.kind,
            subject: round.subject,
            imageFile: round.imageFile,
            sourceUrl: round.sourceUrl,
            snippet: round.snippet,
            snippetLanguage: round.snippetLanguage,
            createdAt: now,
            timesServed: served ? 1 : 0,
            lastServedAt: served ? now : null,
          })
          .returning({ id: rounds.id });
        if (inserted === undefined) throw new Error("insert returned no row");

        await tx.insert(roundTexts).values(
          languages.flatMap((language) => {
            const text = round.texts[language];
            return text === undefined ? [] : [toTextRow(inserted.id, language, text)];
          }),
        );

        return true;
      });
    },

    async draw(topic, language, excludeAnswers, now) {
      const excludeKeys = excludeAnswers.map(answerKey);
      // Joined rather than filtered after the fact: a round with no text in
      // this language is a round this lobby cannot be shown, so drawing it and
      // then discarding it would deal the topic's rotation to nobody.
      const picked = await open()
        .select({
          id: rounds.id,
          topic: rounds.topic,
          kind: rounds.kind,
          subject: rounds.subject,
          imageFile: rounds.imageFile,
          sourceUrl: rounds.sourceUrl,
          snippet: rounds.snippet,
          snippetLanguage: rounds.snippetLanguage,
        })
        .from(rounds)
        .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
        .where(
          and(
            eq(rounds.topic, topic),
            eq(roundTexts.language, language),
            ...(excludeKeys.length > 0 ? [notInArray(roundTexts.answerKey, excludeKeys)] : []),
          ),
        )
        .orderBy(
          asc(rounds.timesServed),
          asc(sql`COALESCE(${rounds.lastServedAt}, 0)`),
          sql`RANDOM()`,
        )
        .limit(1);

      const row = picked[0];
      if (row === undefined) return null;

      await open()
        .update(rounds)
        .set({ timesServed: sql`${rounds.timesServed} + 1`, lastServedAt: now })
        .where(eq(rounds.id, row.id));

      return toBankedRound(row, await textsFor(row.id));
    },

    async count(topic, language) {
      const [row] = await open()
        .select({ n: count() })
        .from(rounds)
        .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
        .where(and(eq(rounds.topic, topic), eq(roundTexts.language, language)));
      return row?.n ?? 0;
    },

    async answers(topic) {
      const rows = await open()
        .select({ answer: roundTexts.answer })
        .from(rounds)
        .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
        .where(eq(rounds.topic, topic))
        .orderBy(asc(rounds.id), asc(roundTexts.language));
      return rows.map((row) => row.answer);
    },

    async aliases(topic) {
      const rows = await open()
        .select({ aliases: roundTexts.aliases })
        .from(rounds)
        .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
        .where(eq(rounds.topic, topic))
        .orderBy(asc(rounds.id), asc(roundTexts.language));
      return rows.flatMap((row) => row.aliases);
    },

    async recordVote(vote) {
      // One insert and no lock: rows are only ever added, so two servers
      // voting on the same round at once have nothing to interleave. The
      // foreign key is the one check — a round the admin has just deleted
      // refuses the row, which is the right answer.
      await open().insert(roundVotes).values({
        roundId: vote.roundId,
        language: vote.language,
        vote: vote.vote,
        createdAt: vote.at,
      });
    },

    async list(filter, page, order = "newest") {
      const db = open();
      /** A text row of *this* round, for the two per-language questions below. */
      const ownText = (language: LanguageId) =>
        db
          .select({ one: sql`1` })
          .from(roundTexts)
          .where(and(eq(roundTexts.roundId, rounds.id), eq(roundTexts.language, language)));

      const conditions: SQL[] = [];
      if (filter.topic !== undefined) conditions.push(eq(rounds.topic, filter.topic));
      if (filter.kind !== undefined) conditions.push(eq(rounds.kind, filter.kind));
      if (filter.language !== undefined) conditions.push(exists(ownText(filter.language)));
      if (filter.missingLanguage !== undefined) conditions.push(notExists(ownText(filter.missingLanguage)));

      const term = filter.search?.trim() ?? "";
      if (term !== "") {
        const pattern = containing(term);
        const answered = db
          .select({ one: sql`1` })
          .from(roundTexts)
          .where(and(eq(roundTexts.roundId, rounds.id), ilike(roundTexts.answer, pattern)));
        conditions.push(or(ilike(rounds.subject, pattern), exists(answered))!);
      }
      const where = conditions.length > 0 ? and(...conditions) : undefined;

      const [[counted], rows] = await Promise.all([
        db.select({ n: count() }).from(rounds).where(where),
        db
          .select(recordColumns)
          .from(rounds)
          .where(where)
          .orderBy(...ordering(order))
          .limit(page.limit)
          .offset(page.offset),
      ]);

      const found = rows.map((row) => row.id);
      const [texts, votes] = await Promise.all([textsForAll(db, found), votesForAll(db, found)]);
      return {
        rounds: rows.map((row) => toRecord(row, texts.get(row.id) ?? {}, votes.get(row.id) ?? NO_VOTES)),
        total: counted?.n ?? 0,
      };
    },

    async get(id) {
      return recordFor(open(), id);
    },

    async update(id, patch) {
      return await open().transaction(async (tx) => {
        const [current] = await tx
          .select({ topic: rounds.topic })
          .from(rounds)
          .where(eq(rounds.id, id))
          .limit(1);
        if (current === undefined) return { ok: false, reason: "not_found" } as const;

        // The same lock `insert` takes, on the shelf the round will be on:
        // the fill tool may be banking into this topic right now, and the
        // clash check below has to see its round or be seen by its check.
        const topic = patch.topic ?? current.topic;
        await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${topic}))`);

        const merged = await textsFor(id, tx);
        const patched = Object.entries(patch.texts ?? {}) as [LanguageId, BankedRoundText | null][];
        for (const [language, text] of patched) {
          if (text === null) delete merged[language];
          else merged[language] = text;
        }
        const languages = Object.keys(merged) as LanguageId[];
        if (languages.length === 0) return { ok: false, reason: "no_texts" } as const;

        // A clash is checked where this edit could have made one: the
        // languages it rewrote, or all of them when the round is moving to
        // another shelf. An untouched language on an unmoved round cannot
        // clash with anything it did not already clash with — and `insert`
        // saw to it that it never did.
        const moved = topic !== current.topic;
        const check = moved ? languages : patched.flatMap(([language]) => (merged[language] ? [language] : []));
        for (const language of check) {
          const text = merged[language];
          if (text === undefined) continue;
          const clash = await clashFor(tx, topic, language, text.answer, id);
          if (clash !== null) {
            return { ok: false, reason: "duplicate", language, answer: clash.answer, roundId: clash.id } as const;
          }
        }

        const set: Partial<typeof rounds.$inferInsert> = {};
        if (patch.topic !== undefined) set.topic = patch.topic;
        if (patch.subject !== undefined) set.subject = patch.subject;
        if (patch.imageFile !== undefined) set.imageFile = patch.imageFile;
        if (patch.sourceUrl !== undefined) set.sourceUrl = patch.sourceUrl;
        if (patch.snippet !== undefined) set.snippet = patch.snippet;
        if (patch.snippetLanguage !== undefined) set.snippetLanguage = patch.snippetLanguage;
        if (Object.keys(set).length > 0) {
          await tx.update(rounds).set(set).where(eq(rounds.id, id));
        }

        if (patched.length > 0) {
          // Replaced rather than updated in place: a language row is small,
          // and delete-then-insert is one shape for "changed", "added" and
          // "removed" alike.
          await tx.delete(roundTexts).where(
            and(
              eq(roundTexts.roundId, id),
              inArray(
                roundTexts.language,
                patched.map(([language]) => language),
              ),
            ),
          );
          const inserts = patched.flatMap(([language, text]) =>
            text === null ? [] : [toTextRow(id, language, text)],
          );
          if (inserts.length > 0) await tx.insert(roundTexts).values(inserts);
        }

        return { ok: true } as const;
      });
    },

    async delete(id) {
      const [gone] = await deleteMany([id]);
      return gone ?? null;
    },

    deleteMany,

    async imageReferences(imageFile) {
      const [row] = await open()
        .select({ n: count() })
        .from(rounds)
        .where(eq(rounds.imageFile, imageFile));
      return row?.n ?? 0;
    },

    async stock() {
      const db = open();
      const [perTopic, perLanguage] = await Promise.all([
        db.select({ topic: rounds.topic, n: count() }).from(rounds).groupBy(rounds.topic),
        db
          .select({ topic: rounds.topic, language: roundTexts.language, n: count() })
          .from(rounds)
          .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
          .groupBy(rounds.topic, roundTexts.language),
      ]);

      const byTopic = new Map<string, TopicStock>();
      const shelf = (topic: string): TopicStock => {
        let own = byTopic.get(topic);
        if (own === undefined) {
          own = { topic: topic as TopicId, rounds: 0, counts: {} };
          byTopic.set(topic, own);
        }
        return own;
      };
      // Catalogue first, so the order is the one every other screen uses;
      // whatever the bank holds beyond it follows in its own order.
      for (const topic of ALL_TOPIC_IDS) shelf(topic);
      for (const row of perTopic) shelf(row.topic).rounds = row.n;
      for (const row of perLanguage) shelf(row.topic).counts[row.language as LanguageId] = row.n;
      return [...byTopic.values()];
    },

    async close() {
      db = null;
      await options.end();
    },
  };
}

/**
 * The production bank: a small `pg` pool on the one Postgres both processes
 * share. Small on purpose — the game server's queries are indexed point reads
 * and single-row writes, and the fill tool banks one round at a time; a
 * connection this database does not need is one another process cannot have.
 */
export function createPostgresRoundRepository(connectionString: string): RoundRepository {
  let pool: pg.Pool | null = null;

  return createDrizzleRoundRepository({
    async connect() {
      pool = new pg.Pool({ connectionString, max: 5 });
      const db = drizzle(pool);
      await migrate(db, { migrationsFolder });
      return db;
    },
    async end() {
      await pool?.end();
      pool = null;
    },
  });
}
