import { fileURLToPath } from "node:url";
import { and, asc, count, eq, notInArray, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
import pg from "pg";
import type { LanguageId, RoundKind, TopicId } from "@guessly/protocol";
import {
  answerKey,
  type BankedRound,
  type NewBankedRound,
  type RoundRepository,
} from "./repository.js";
import { rounds, roundTexts } from "./schema.js";

/**
 * The bank on Postgres, through Drizzle. Right for what the bank actually is:
 * one database written by the fill tool and read by the game server — two
 * processes that used to share a SQLite file politely and now share a server
 * built for exactly that.
 *
 * The schema lives in `schema.ts` and the SQL that builds it in `drizzle/`,
 * generated by `drizzle-kit generate` from the same file the queries import —
 * so the tables the migrations make are the tables the queries mean, by
 * construction. `init()` applies whatever is pending, which keeps the old
 * contract: everything after it may assume the schema is there.
 *
 * The same queries serve two databases: the real one over `pg`, and — for the
 * tests — PGlite, which is Postgres itself compiled to WASM, not an imitation
 * of it. See `memory.ts`. This type is the seam between them: everything both
 * drivers can do, and everything the repository needs.
 */
export type BankDatabase = PgDatabase<PgQueryResultHKT, Record<string, never>>;

/** Where `drizzle-kit generate` writes: one level up from src/ and dist/ alike. */
export const migrationsFolder = fileURLToPath(new URL("../drizzle", import.meta.url));

const toBankedRound = (
  row: {
    id: number;
    topic: string;
    kind: string;
    subject: string;
    imageFile: string | null;
    sourceUrl: string | null;
    snippet: string | null;
    snippetLanguage: string | null;
  },
  texts: BankedRound["texts"],
): BankedRound => ({
  id: row.id,
  topic: row.topic as TopicId,
  kind: row.kind as RoundKind,
  subject: row.subject,
  imageFile: row.imageFile,
  sourceUrl: row.sourceUrl,
  snippet: row.snippet,
  snippetLanguage: row.snippetLanguage,
  texts,
});

/**
 * The repository's queries, against whichever Postgres the caller opened.
 * `open` insists init() ran first; `end` is the driver's own goodbye.
 */
export function createDrizzleRoundRepository(options: {
  connect: () => Promise<BankDatabase>;
  end: () => Promise<void>;
}): RoundRepository {
  let db: BankDatabase | null = null;

  /** Init is the only place `db` is assigned; everything else may insist on it. */
  const open = (): BankDatabase => {
    if (db === null) throw new Error("round repository used before init()");
    return db;
  };

  /** Every language one round was written in, gathered back into one object. */
  const textsFor = async (roundId: number): Promise<BankedRound["texts"]> => {
    const rows = await open()
      .select({
        language: roundTexts.language,
        question: roundTexts.question,
        answer: roundTexts.answer,
        aliases: roundTexts.aliases,
      })
      .from(roundTexts)
      .where(eq(roundTexts.roundId, roundId))
      .orderBy(asc(roundTexts.language));

    const texts: BankedRound["texts"] = {};
    for (const row of rows) {
      texts[row.language as LanguageId] = {
        question: row.question,
        answer: row.answer,
        aliases: row.aliases,
      };
    }
    return texts;
  };

  return {
    async init() {
      db = await options.connect();
    },

    async insert(round: NewBankedRound, now: number, served: boolean) {
      const languages = Object.keys(round.texts) as LanguageId[];
      if (languages.length === 0) return false;

      // Checked, then written, under a transaction-scoped advisory lock on
      // the topic: the fill tool and the game server are separate processes
      // on one database, and the lock is what keeps a check and its insert
      // from interleaving with another writer's — the same promise BEGIN
      // IMMEDIATE used to make, scoped to the one topic being written. The
      // check is a check rather than a unique index because the answer being
      // looked for lives one table away from the topic that scopes it.
      return await open().transaction(async (tx) => {
        await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${round.topic}))`);

        for (const language of languages) {
          const text = round.texts[language];
          if (text === undefined) continue;
          const clash = await tx
            .select({ id: roundTexts.roundId })
            .from(roundTexts)
            .innerJoin(rounds, eq(rounds.id, roundTexts.roundId))
            .where(
              and(
                eq(rounds.topic, round.topic),
                eq(roundTexts.language, language),
                eq(roundTexts.answerKey, answerKey(text.answer)),
              ),
            )
            .limit(1);
          if (clash.length > 0) return false;
        }

        const [inserted] = await tx
          .insert(rounds)
          .values({
            topic: round.topic,
            kind: round.kind,
            subject: round.subject,
            imageFile: round.imageFile,
            sourceUrl: round.sourceUrl,
            snippet: round.snippet,
            snippetLanguage: round.snippetLanguage,
            createdAt: now,
            timesServed: served ? 1 : 0,
            lastServedAt: served ? now : null,
          })
          .returning({ id: rounds.id });
        if (inserted === undefined) throw new Error("insert returned no row");

        await tx.insert(roundTexts).values(
          languages.flatMap((language) => {
            const text = round.texts[language];
            if (text === undefined) return [];
            return [
              {
                roundId: inserted.id,
                language,
                question: text.question,
                answer: text.answer,
                answerKey: answerKey(text.answer),
                aliases: text.aliases,
              },
            ];
          }),
        );

        return true;
      });
    },

    async draw(topic, language, excludeAnswers, now) {
      const excludeKeys = excludeAnswers.map(answerKey);
      // Joined rather than filtered after the fact: a round with no text in
      // this language is a round this lobby cannot be shown, so drawing it and
      // then discarding it would deal the topic's rotation to nobody.
      const picked = await open()
        .select({
          id: rounds.id,
          topic: rounds.topic,
          kind: rounds.kind,
          subject: rounds.subject,
          imageFile: rounds.imageFile,
          sourceUrl: rounds.sourceUrl,
          snippet: rounds.snippet,
          snippetLanguage: rounds.snippetLanguage,
        })
        .from(rounds)
        .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
        .where(
          and(
            eq(rounds.topic, topic),
            eq(roundTexts.language, language),
            ...(excludeKeys.length > 0 ? [notInArray(roundTexts.answerKey, excludeKeys)] : []),
          ),
        )
        .orderBy(
          asc(rounds.timesServed),
          asc(sql`COALESCE(${rounds.lastServedAt}, 0)`),
          sql`RANDOM()`,
        )
        .limit(1);

      const row = picked[0];
      if (row === undefined) return null;

      await open()
        .update(rounds)
        .set({ timesServed: sql`${rounds.timesServed} + 1`, lastServedAt: now })
        .where(eq(rounds.id, row.id));

      return toBankedRound(row, await textsFor(row.id));
    },

    async count(topic, language) {
      const [row] = await open()
        .select({ n: count() })
        .from(rounds)
        .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
        .where(and(eq(rounds.topic, topic), eq(roundTexts.language, language)));
      return row?.n ?? 0;
    },

    async answers(topic) {
      const rows = await open()
        .select({ answer: roundTexts.answer })
        .from(rounds)
        .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
        .where(eq(rounds.topic, topic))
        .orderBy(asc(rounds.id), asc(roundTexts.language));
      return rows.map((row) => row.answer);
    },

    async aliases(topic) {
      const rows = await open()
        .select({ aliases: roundTexts.aliases })
        .from(rounds)
        .innerJoin(roundTexts, eq(roundTexts.roundId, rounds.id))
        .where(eq(rounds.topic, topic))
        .orderBy(asc(rounds.id), asc(roundTexts.language));
      return rows.flatMap((row) => row.aliases);
    },

    async close() {
      db = null;
      await options.end();
    },
  };
}

/**
 * The production bank: a small `pg` pool on the one Postgres both processes
 * share. Small on purpose — the game server's queries are indexed point reads
 * and single-row writes, and the fill tool banks one round at a time; a
 * connection this database does not need is one another process cannot have.
 */
export function createPostgresRoundRepository(connectionString: string): RoundRepository {
  let pool: pg.Pool | null = null;

  return createDrizzleRoundRepository({
    async connect() {
      pool = new pg.Pool({ connectionString, max: 5 });
      const db = drizzle(pool);
      await migrate(db, { migrationsFolder });
      return db;
    },
    async end() {
      await pool?.end();
      pool = null;
    },
  });
}
