CREATE TABLE "round_texts" (
	"round_id" integer NOT NULL,
	"language" text NOT NULL,
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"answer_key" text NOT NULL,
	"aliases" jsonb NOT NULL,
	CONSTRAINT "round_texts_round_id_language_pk" PRIMARY KEY("round_id","language")
);
--> statement-breakpoint
CREATE TABLE "rounds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rounds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"topic" text NOT NULL,
	"kind" text NOT NULL,
	"subject" text NOT NULL,
	"image_file" text,
	"source_url" text,
	"snippet" text,
	"snippet_language" text,
	"created_at" bigint NOT NULL,
	"times_served" integer DEFAULT 0 NOT NULL,
	"last_served_at" bigint
);
--> statement-breakpoint
ALTER TABLE "round_texts" ADD CONSTRAINT "round_texts_round_id_rounds_id_fk" FOREIGN KEY ("round_id") REFERENCES "public"."rounds"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "round_texts_answer" ON "round_texts" USING btree ("language","answer_key");--> statement-breakpoint
CREATE INDEX "rounds_topic" ON "rounds" USING btree ("topic");