import { createReadStream } from "node:fs";
import { createServer, type ServerResponse } from "node:http";
import { join } from "node:path";
import { Server } from "socket.io";
import { SWEEP_INTERVAL_MS } from "@guessly/protocol";
import { createImageStore } from "./bank/images.js";
import { createBankedRoundSource } from "./bank/source.js";
import { createSqliteRoundRepository } from "./bank/sqlite.js";
import { loadConfig, loadEnvFile } from "./config.js";
import { createClaudeRoundGenerator } from "./content/claude.js";
import { createLobbyStore } from "./lobby/store.js";
import { registerSocketHandlers, type GameServer } from "./socket/register.js";

// Before anything reads process.env. Nothing else loads the file, and turbo
// runs tasks in strict env mode, so this is the only way a local
// ANTHROPIC_API_KEY reaches the process.
loadEnvFile();
const config = loadConfig();

// The bank: rounds in SQLite, pictures on disk, both under one directory that
// is expected to outlive the process — that persistence is the whole point.
const repository = createSqliteRoundRepository(join(config.dataDir, "rounds.db"));
const images = createImageStore(join(config.dataDir, "images"));
await repository.init();
await images.init();

/**
 * Banked images, from our own origin. The filename is content-addressed and
 * validated by the store, so an unknown or malformed name is a 404 before the
 * filesystem is consulted, and a known one can be cached forever — different
 * picture, different name.
 */
const serveImage = (filename: string, res: ServerResponse): void => {
  const found = images.resolve(filename);
  if (found === null) {
    res.writeHead(404, { "content-type": "text/plain" });
    res.end("Not found");
    return;
  }

  const stream = createReadStream(found.path);
  stream.on("error", () => {
    // Banked but missing on disk — a wiped image directory next to a kept
    // database. The browser's onError is the last mile, same as ever.
    if (!res.headersSent) res.writeHead(404, { "content-type": "text/plain" });
    res.end();
  });
  stream.once("open", () => {
    res.writeHead(200, {
      "content-type": found.contentType,
      "cache-control": "public, max-age=31536000, immutable",
      "x-content-type-options": "nosniff",
    });
    stream.pipe(res);
  });
};

const httpServer = createServer((req, res) => {
  if (req.url === "/health") {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: true }));
    return;
  }

  if (req.url?.startsWith("/img/")) {
    serveImage(req.url.slice("/img/".length), res);
    return;
  }

  res.writeHead(404, { "content-type": "text/plain" });
  res.end("Not found");
});

const io: GameServer = new Server(httpServer, {
  cors: { origin: config.allowedOrigins, methods: ["GET", "POST"] },
  /**
   * Nothing in this protocol is larger than a nickname and a lobby code, so a
   * megabyte of default headroom is a megabyte of attack surface.
   */
  maxHttpBufferSize: 8_192,
});

const store = createLobbyStore();
const generator = createClaudeRoundGenerator({
  apiKey: config.anthropicApiKey,
  model: config.anthropicModel,
});
const source = createBankedRoundSource({
  repository,
  images,
  generator,
  publicBaseUrl: config.publicBaseUrl,
});
const adapter = registerSocketHandlers(io, store, source);

/**
 * The lobby's timer. Grace periods and both lobby TTLs are all evaluated here,
 * which is what lets the store stay pure and testable with a fake clock instead
 * of a fleet of setTimeouts. Rounds have their own, short-lived timers — see
 * game/rounds.ts — because a countdown cannot wait up to a minute to be noticed.
 */
const sweepTimer = setInterval(() => {
  try {
    adapter.sweep();
  } catch (error) {
    console.error("[game] sweep failed", error);
  }
}, SWEEP_INTERVAL_MS);

httpServer.listen(config.port, () => {
  console.log(`[game] listening on :${config.port}`);
  console.log(`[game] allowed origins: ${config.allowedOrigins.join(", ")}`);
  console.log(`[game] rounds generated by ${config.anthropicModel}`);
  console.log(`[game] round bank at ${config.dataDir}, images served from ${config.publicBaseUrl}/img/`);
});

const shutdown = (signal: string) => {
  console.log(`[game] ${signal} received, closing`);
  clearInterval(sweepTimer);
  io.close(() => {
    httpServer.close(() => {
      // Background top-ups first, then the database under them.
      void source
        .close()
        .then(() => repository.close())
        .finally(() => process.exit(0));
    });
  });
};

process.on("SIGINT", () => shutdown("SIGINT"));
process.on("SIGTERM", () => shutdown("SIGTERM"));
